<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasileiro)
// Author of the language pack : Leandro dos Santos
// Language pack translators website : http://www.hospedagemecriacaodesites.com.br/
// Compatible version of MyBB : 1800
// Last edited in MyBB Editor by : Saulo Henrique
// Last edited date : Sun, 07 Dec 2014 21:18:46 +0000
// --------------------------------------------------------------------------------

$l['nav_reputation'] = 'Relatório de Reputação';
$l['nav_profile'] = 'Perfil de {1}';
$l['reputation_disabled'] = 'Você não pode usar o sistema de reputação uma vez que o mesmo foi desativado por um administrador.';
$l['reputation'] = 'Reputação';
$l['error'] = 'Erro';
$l['add_no_uid'] = 'Você não selecionou nenhum usuário para dar reputação.';
$l['add_no_permission'] = 'Você não tem permissão para votar na reputação de outros usuários.';
$l['add_disabled'] = 'Você não pode votar na reputação dos usuários deste grupo.';
$l['add_yours'] = 'Você não pode votar na sua própria reputação.';
$l['add_invalidpower'] = 'Você selecionou uma opção de votação inválida.';
$l['add_maxperday'] = 'Você atingiu o máximo de pontos de reputação que pode atribuir diariamente.';
$l['add_maxperuser'] = 'Você já atribuiu a este usuário o máximo de pontos de reputação que pode atribuir diariamente.';
$l['add_maxperthread'] = 'Você já atribuiu a este usuário o máximo de pontos de reputação (num só tópico) que pode atribuir diariamente.';
$l['add_no_comment'] = 'Você deve inserir um comentário de pelo menos 10 caracteres, para avaliar a reputação de este usuário.';
$l['add_toolong'] = 'Você tem de inserir uma razão, que não contenha mais de {1} caracteres.';
$l['add_negative_disabled'] = 'O Administrador desativou as reputações negativas.';
$l['add_neutral_disabled'] = ' O Administrador desativou as reputações neutras.';
$l['add_positive_disabled'] = ' O Administrador desativou as reputações positivas.';
$l['add_all_rep_disabled'] = ' O Administrador desativou todo o tipo de reputações. Você não pode avaliar este usuário.';
$l['reputation_report'] = 'Relatório de Reputação de {1}';
$l['reputation_members'] = 'Reputação de Membros:';
$l['reputation_posts'] = 'Reputação de Mensagens:';
$l['summary'] = 'Sumário';
$l['total_reputation'] = 'Reputação Total';
$l['post_reputation'] = 'Reputação de Postagens';
$l['positive_count'] = 'Positivas';
$l['neutral_count'] = 'Neutras';
$l['negative_count'] = 'Negativas';
$l['last_week'] = 'Última Semana';
$l['last_month'] = 'Último Mês';
$l['last_6months'] = 'Últimos 6 meses';
$l['comments'] = 'Comentários';
$l['close_window'] = 'Fechar Janela';
$l['add_reputation_vote'] = 'Adicionar uma avaliação de reputação de {1}';
$l['add_reputation_to_post'] = 'Esta reputação é para a mensagem de {1}.<br />';
$l['neg_rep_disabled'] = '<span class="smalltext">* - <em>A reputação negativa está desativada no momento</em></span>';
$l['pos_rep_disabled'] = '<span class="smalltext">* - <em> A reputação positiva está desativada no momento </em></span>';
$l['neu_rep_disabled'] = '<span class="smalltext">* - <em> A reputação neutra está desativada no momento </em></span>';
$l['no_comment_needed'] = 'Você está editando a reputação, devido às mensagens deste(s) usuário(s), que está ligada aos seus perfis. Não é necessário um comentário, mas se quiser pode deixar um, por favor, insira-o abaixo.<br />';
$l['no_comment'] = '[Sem comentário]';
$l['vote_added'] = 'Avaliação Adicionada';
$l['vote_updated'] = 'Avaliação Atualizada';
$l['vote_deleted'] = 'Avaliação Apagada';
$l['vote_added_message'] = 'A sua avaliação de reputação foi adicionada com sucesso para este usuário.';
$l['vote_updated_message'] = 'A sua avaliação de reputação foi atualizada com sucesso para este usuário.';
$l['vote_deleted_message'] = 'A avaliação de reputação  foi apagada com sucesso para este usuário.';
$l['update_reputation_vote'] = 'Atualizar avaliação de reputação de {1}';
$l['positive'] = 'Positiva';
$l['negative'] = 'Negativa';
$l['neutral'] = 'Neutra';
$l['user_comments'] = 'Os seus comentários em {1}:';
$l['add_vote'] = 'Adicionar Avaliação';
$l['update_vote'] = 'Atualizar Avaliação';
$l['delete_vote'] = 'Eliminar Avaliação';
$l['report_vote'] = 'Denunciar';
$l['power_positive'] = 'Positiva ({1})';
$l['power_neutral'] = 'Neutra';
$l['power_negative'] = 'Negativa ({1})';
$l['show_all'] = 'Visualizar: Todos os Votos';
$l['show_positive'] = 'Mostrar: Avaliações Positivas';
$l['show_neutral'] = 'Mostrar: Avaliações Neutras';
$l['show_negative'] = 'Mostrar: Avaliações Negativas';
$l['sort_updated'] = 'Ordenar por: Última Atualização';
$l['sort_username'] = 'Ordenar por: Nome de Usuário';
$l['last_updated'] = 'Última Atualização {1}';
$l['postrep_given'] = 'Classificação dada para <a href="{1}"> {2} após </a> {3} <br />';
$l['no_reputation_votes'] = 'Este usuário, não tem nenhuma avaliação de reputação no momento, de acordo com o critério especificado abaixo.';
$l['delete_reputation_confirm'] = 'Tem  a certeza que quer apagar esta avaliação de reputação?';
$l['delete_reputation_log'] = 'Reputação removida por {1} (UID: {2})';
$l['reputations_disabled_group'] = 'O sistema de reputação está desativado para usuários deste Grupo.';
$l['rate_user'] = 'Avaliar Usuário';
$l['all_time'] = 'Tempo Integral';
$l['postrep_given_thread'] = 'em <a href="{1}"> {2} </a>';
